labels:
  - name: bug
    color: d73a4a
    description: Something is not working
  - name: enhancement
    color: a2eeef
    description: New feature or request
  - name: good first issue
    color: 7057ff
    description: Good for newcomers
  - name: roadmap
    color: 0e8a16
    description: Tracked on the public roadmap
