blank_issues_enabled: false
contact_links:
  - name: Security vulnerabilities
    url: mailto:security@aidb.dev
    about: Please report security vulnerabilities privately.
  - name: Community chat
    url: https://matrix.to/#/#aidb:matrix.org
    about: Join the community channel for quick questions.
